-- Step 1: add enum values and new enum types (must commit before data migration).

DO $$ BEGIN
  CREATE TYPE "OrderSource" AS ENUM ('QR_ORDER', 'STAFF_CREATED', 'WALK_IN', 'PHONE_ORDER', 'RESERVATION', 'DELIVERY_PARTNER');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "OrderPaymentStatus" AS ENUM ('UNPAID', 'PENDING', 'PAID', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "OrderActorSource" AS ENUM ('CUSTOMER', 'STAFF', 'SYSTEM', 'PAYMENT', 'ADMIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
